export let states = [
	{ name: 'Acre', src: '/data/geojson-enriched/Acre.json' },
	{ name: 'Alagoas', src: '/data/geojson-enriched/Alagoas.json' },
	{ name: 'Amapá', src: '/data/geojson-enriched/Amapa.json' },
	{ name: 'Amazonas', src: '/data/geojson-enriched/Amazonas.json' },
	{ name: 'Bahia', src: '/data/geojson-enriched/Bahia.json' },
	{ name: 'Ceará', src: '/data/geojson-enriched/Ceara.json' },
	{ name: 'Distrito Federal', src: '/data/geojson-enriched/DistritoFederal.json' },
	{ name: 'Espírito Santo', src: '/data/geojson-enriched/EspiritoSanto.json' },
	{ name: 'Goiás', src: '/data/geojson-enriched/Goias.json' },
	{ name: 'Maranhão', src: '/data/geojson-enriched/Maranhao.json' },
	{ name: 'Mato Grosso', src: '/data/geojson-enriched/MatoGrosso.json' },
	{ name: 'Mato Grosso do Sul', src: '/data/geojson-enriched/MatoGrossoDoSul.json' },
	{ name: 'Minas Gerais', src: '/data/geojson-enriched/MinasGerais.json' },
	{ name: 'Pará', src: '/data/geojson-enriched/Para.json' },
	{ name: 'Paraíba', src: '/data/geojson-enriched/Paraiba.json' },
	{ name: 'Paraná', src: '/data/geojson-enriched/Parana.json' },
	{ name: 'Pernambuco', src: '/data/geojson-enriched/Pernambuco.json' },
	{ name: 'Piauí', src: '/data/geojson-enriched/Piaui.json' },
	{ name: 'Rio de Janeiro', src: '/data/geojson-enriched/RioDeJaneiro.json' },
	{ name: 'Rio Grande do Norte', src: '/data/geojson-enriched/RioGrandeDoNorte.json' },
	{ name: 'Rio Grande do Sul', src: '/data/geojson-enriched/RioGrandeDoSul.json' },
	{ name: 'Rondônia', src: '/data/geojson-enriched/Rondonia.json' },
	{ name: 'Roraima', src: '/data/geojson-enriched/Roraima.json' },
	{ name: 'Santa Catarina', src: '/data/geojson-enriched/SantaCatarina.json' },
	{ name: 'São Paulo', src: '/data/geojson-enriched/SaoPaulo.json' },
	{ name: 'Sergipe', src: '/data/geojson-enriched/Sergipe.json' },
	{ name: 'Tocantins', src: '/data/geojson-enriched/Tocantins.json' }
];